import SwiftUI

/// Calls the built-in macOS About panel with custom credits content.
/// Authors are read from the AUTHORS file generated at build time by build_app.sh.
func showAboutPanel() {
    let version = Bundle.main.infoDictionary?["CFBundleShortVersionString"] as? String ?? "Development"
    let year = String(Calendar.current.component(.year, from: Date()))

    // Read contributors from bundled AUTHORS file (generated by git shortlog at build time)
    let authors: [String]
    if let authorsPath = Bundle.main.path(forResource: "AUTHORS", ofType: nil),
       let content = try? String(contentsOfFile: authorsPath, encoding: .utf8) {
        authors = content.components(separatedBy: .newlines).map { $0.trimmingCharacters(in: .whitespaces) }.filter { !$0.isEmpty }
    } else {
        // Fallback to the repo owner when running outside the built bundle (e.g. swift run)
        authors = ["Adam Scarcella"]
    }

    let credits = NSMutableAttributedString()

    // Spacer before quote
    credits.append(NSAttributedString(string: "\n"))

    // Quote
    let quoteStyle = NSMutableParagraphStyle()
    quoteStyle.alignment = .center
    quoteStyle.paragraphSpacing = 14
    credits.append(NSAttributedString(
        string: "\u{201C}You\u{2019}re only limited by your imagination!\u{201D}\n\n",
        attributes: [
            .font: NSFont(name: "Georgia-Italic", size: 13) ?? NSFont.systemFont(ofSize: 13),
            .foregroundColor: NSColor.labelColor,
            .paragraphStyle: quoteStyle,
        ]
    ))

    // Authors header
    let headerStyle = NSMutableParagraphStyle()
    headerStyle.alignment = .center
    headerStyle.paragraphSpacing = 6
    credits.append(NSAttributedString(
        string: "Authors\n",
        attributes: [
            .font: NSFont.boldSystemFont(ofSize: 11),
            .foregroundColor: NSColor.secondaryLabelColor,
            .paragraphStyle: headerStyle,
        ]
    ))

    // Author list (from git shortlog)
    let authorStyle = NSMutableParagraphStyle()
    authorStyle.alignment = .center
    authorStyle.paragraphSpacing = 3
    for name in authors {
        credits.append(NSAttributedString(
            string: "\(name)\n",
            attributes: [
                .font: NSFont.systemFont(ofSize: 12, weight: .medium),
                .foregroundColor: NSColor.labelColor,
                .paragraphStyle: authorStyle,
            ]
        ))
    }

    NSApplication.shared.orderFrontStandardAboutPanel(options: [
        .applicationName:    "Boomi SRE",
        .applicationVersion: "Version \(version)",
        .version:            "",
        .credits:            credits,
        NSApplication.AboutPanelOptionKey(rawValue: "Copyright"): "© \(year) Boomi, Ltd. All rights reserved.",
    ])
}
